# Generated by Django 3.1.4 on 2020-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stores',
            name='identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
