# Generated by Django 3.1.4 on 2020-12-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_auto_20201212_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='deals',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
