# Generated by Django 3.1.4 on 2020-12-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='idfb',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
